### ISSUE TITLE
App crashes after sync library dependencies

### ISSUE THREAD

**Issue by ahmednasserzaza** [mirzemehdi/KMPNotifier#1]
My app is Crashing at run time (onCreate method) after adding all dependecies required in docs 
When I removed library dependency ,the app works well.

![Untitled](https://github.com/mirzemehdi/KMPNotifier/assets/30028905/9256c029-c77b-4959-a923-2f5c6cdbb93b)

**Comment by mirzemehdi** [comment]
Do you use koin library in your app?. If you use which version do you use @ahmednasserzaza ?

**Comment by ahmednasserzaza** [comment]
@mirzemehdi 
Yes,
here are all the versions I use:

koin-version = "3.4.3"
koin-compose-version = "1.0.4"
koinKspVersion = "1.2.2"

**Comment by mirzemehdi** [comment]
@ahmednasserzaza Could you please make these steps if possible and see if this still continues? Sometimes when different koin versions are used this can occur
1) Upgrade koin version to 3.5.0
2) Invalidate cache and restart
