### ISSUE TITLE
Notifications are displayed when app is in Foreground in Android

### ISSUE THREAD

**Issue by koushikvkk** [mirzemehdi/KMPNotifier#13]
Instead of directly building and displaying notifications when a notification message is sent, can we allow the consumer app to handle the processing in its own way?
Sample I tried https://github.com/koushikvkk/KMPNotifier/pull/1. Let me know your thoughts about this change

**Comment by mirzemehdi** [comment]
@koushikvkk it is a nice suggestion in fact. But we need also to think about to do same for iOS side as well. I'll add this to next milestone. Thank you for this feature suggestion.

**Comment by mirzemehdi** [comment]
@koushikvkk This is implemented in version **0.4.0**
You can check description of pull request for usage: https://github.com/mirzemehdi/KMPNotifier/pull/15.
Thanks again for this feature suggestion.

**Comment by koushikvkk** [comment]
Thank you very much for taking my request into consideration. @mirzemehdi.

**Comment by koushikvkk** [comment]
Sure.
In my initial testing, everything seems to be working well without any issues.
