### ISSUE TITLE
 How do I retrieve payload data if the app is in the background?

### ISSUE THREAD

**Issue by BehnamMaboodi** [mirzemehdi/KMPNotifier#18]
I can read payload data with the listener mentioned in the documentation. However, when the app is closed and I tap on a notification, the app opens, but I only see this in the log:

```
Received Push Notification payload data
There is no listener to notify onPushPayloadData
```

I currently set the listeners in the view model. Where should I set the listener to resolve this issue?

**Comment by mirzemehdi** [comment]
The best place to put listeners is onApplicationStart method

**Comment by mirzemehdi** [comment]
@BehnamMaboodi you can check this sample: https://github.com/mirzemehdi/KMPNotifier/blob/main/sample/src/commonMain/kotlin/com/mmk/kmpnotifier/sample/AppInitializer.kt
