### ISSUE TITLE
How can I track the opening of app by clicking on a notification?

### ISSUE THREAD

**Issue by GimazDo** [mirzemehdi/KMPNotifier#19]
Hi, how can i detect that user clicked on notification? 

I need that when I click on a notification, a screen will open depending on the data in the notification.

**Comment by Abdelrhman-sbs** [comment]
@ValdZX @mirzemehdi 
Please, any help?

**Comment by mirzemehdi** [comment]
I think this is more about adding deeplink support to library. But I am still checking my options

**Comment by mirzemehdi** [comment]
Please, let me know if there is any issue

**Comment by emanuelecastelli** [comment]
On my side (ios impl) `onNotificationClicked ` callback not get called when app is in background. 
I have followed all the conf steps and tried to use `UNUserNotificationCenterDelegate` too, but without luck.
Can you confirm that package callback is triggered when app is in background?

**Comment by mirzemehdi** [comment]
@emanuelecastelli yes, when I click notification I get listener callback.

1) Make sure you enabled remote-notificaiton in backgorund modes in XCode.
2) You added this part in ios part
```swift
func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any]) async -> UIBackgroundFetchResult {
        NotifierManager.shared.onApplicationDidReceiveRemoteNotification(userInfo: userInfo)
        return UIBackgroundFetchResult.newData
    }
```

**Comment by emanuelecastelli** [comment]
@mirzemehdi can you provide json body that you use for test push notifications?
I'm using something like that, playing with apns props, but no way :(
```json
{
  "message": {
    "token": ".......",
     "notification": {
      "title": "title",
      "body": "Notification from FCM"
    },
    "apns": {
    
        "headers": {
            
            
        },
        "payload": {
            
        }
    }
  }
}
```

**Comment by emanuelecastelli** [comment]
Ok, restoring FCM method swizzling resolve the issue: push notifications callbacks now runs correctly
