### ISSUE TITLE
Request permission optional at init

### ISSUE THREAD

**Issue by corneloaie** [mirzemehdi/KMPNotifier#22]
Hello, I want to inform the user before requesting the permission for notifications which is done now at lib init which is done when the app starts. Could you please make the permission request optional in order to have the possibility to request ourselves this when deemed necessary?  And later as an improvement expose the request permission method so we can use directly your impl.

Thank you for your great work.

**Comment by mirzemehdi** [comment]
@corneloaie I'll consider to implemen this. Thank you!

**Comment by mirzemehdi** [comment]
This is implemented in version `0.6.0`

For more information about usage you can check comment in PR: https://github.com/mirzemehdi/KMPNotifier/pull/27
