### ISSUE TITLE
Breaks with swizzling disabled.

### ISSUE THREAD

**Issue by anuragdalia** [mirzemehdi/KMPNotifier#29]
i want to disable fcm method swizzling in ios for another library[Adjust]. but when i do that there is no way to patch kmp with custom function call/listener to listen to unnotifcenter calls . is the only way forking? basically my deeplink reading is breaking

**Comment by anuragdalia** [comment]
I think if the notifier object wouldn't be internal it would work.

**Comment by mirzemehdi** [comment]
@anuragdalia in Firebase documentation it is shown that adding below method to application method in Swift would work with swizzling disabled. Can you please check it and let me know it it works for you?

```
func application(_ application: UIApplication,
    didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
  Messaging.messaging().apnsToken = deviceToken;
}
```
