### ISSUE TITLE
Could not find "co.touchlab:stately-common"

### ISSUE THREAD

**Issue by omkar-tenkale** [mirzemehdi/KMPNotifier#30]
Android app runs fine but compiling ios app throws build error

Could not find "co.touchlab:stately-common" in [/my/project/path, /Users/me/.konan/klib, /Users/me/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.23/klib/common, /Users/me/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.23/klib/platform/ios_simulator_arm64]

**Comment by omkar-tenkale** [comment]
I had to add
```
implementation("co.touchlab:stately-common:2.0.5")
```

in 
```
commonMain.dependencies {

} 
```
 to make it work

**Comment by mirzemehdi** [comment]
@omkar-tenkale yes as a temporary solution including stately library in common should solve problem. But for next release  I'll bump koin version to latest version and this will solve the issue, thanks for bringing this up

Related issue: https://github.com/InsertKoinIO/koin/issues/1785
