### ISSUE TITLE
Notification Click not working when iOS app is closed

### ISSUE THREAD

**Issue by ivancaas** [mirzemehdi/KMPNotifier#31]
I might be wrong as I'm not an expert in iOS myself. But when I click the notification with the app in Background/Opened it gets to onNotificationClicked, but when the app is closed and I tap, the app opens but nothing happens as it's not calling that function somehow

**Comment by mirzemehdi** [comment]
@ivancaas did you do these steps in ios as it is shown in ReadMe?

##### iOS
Call `NotifierManager.onApplicationDidReceiveRemoteNotification(userInfo: userInfo)` on application's `didReceiveRemoteNotification` method.

```
 func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any]) async -> UIBackgroundFetchResult {
      NotifierManager.shared.onApplicationDidReceiveRemoteNotification(userInfo: userInfo)
      return UIBackgroundFetchResult.newData
 }

```  


#### Detecting notification click and get payload data
Make sure you follow previous step for getting payload data properly.
```kotlin
NotifierManager.addListener(object : NotifierManager.Listener {
    override fun onNotificationClicked(data: PayloadData) {
        super.onNotificationClicked(data)
        println("Notification clicked, Notification payloadData: $data")
    }
}) 
```

**Comment by tamimattafi** [comment]
@mirzemehdi @ivancaas In order to handle start arguments, you need to read user Info from didFinishLaunchingWithOptions
https://github.com/mirzemehdi/KMPNotifier/issues/24#issuecomment-2082659684

**Comment by ivancaas** [comment]
@mirzemehdi was right about something missing, apparently I forgot to add the  "NotifierManager.shared.initialize" line in the iOS App?... too many hours coding, the rest was OK, after adding it everything works as expected.

Thanks both for your help!

**Comment by sereden** [comment]
I have the following setup:
```
import SwiftUI
import Foundation
import FirebaseCore
import FirebaseCrashlytics
import FirebaseMessaging
import ComposeApp

class AppDelegate: NSObject, UIApplicationDelegate {
    func application(_ application: UIApplication,
                   didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        FirebaseApp.configure()
        NSLog("initialize")
        NotifierManager.shared.initialize(configuration: NotificationPlatformConfigurationIos(showPushNotification: true, askNotificationPermissionOnStart: true, notificationSoundName: nil))
      
        if let infoDictionary = Bundle.main.infoDictionary {
            if let buildType = infoDictionary["BuildType"] as? String{
                Crashlytics.crashlytics().setCrashlyticsCollectionEnabled(buildType == "release")
            }
        }
        return true
    }
    
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Messaging.messaging().apnsToken = deviceToken
    }
    
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any]) async -> UIBackgroundFetchResult {
        NSLog("onApplicationDidReceiveRemoteNotification")
         NotifierManager.shared.onApplicationDidReceiveRemoteNotification(userInfo: userInfo)
         return UIBackgroundFetchResult.newData
    }
}
```
onApplicationDidReceiveRemoteNotification is not called when the app was closed. However, `initialize` is always called.
Also, added the following capabilities:
<img width="953" alt="Screenshot 2024-09-20 at 18 25 31" src="https://github.com/user-attachments/assets/7ae4dcca-69f6-462c-be1c-898aa8696dd3">

Any ideas, on what could be a cause?
