### ISSUE TITLE
Q : Can this library be implemented in Compose Multiplatform?

### ISSUE THREAD

**Issue by jsk41755** [mirzemehdi/KMPNotifier#33]
Hi!
Thanks for making such a great library.

I have a question about this library. In Compose Multiplatform, I develop in Shared Module, but I was wondering if I need to develop in Swift like KMM for push notifications to work.
If this doesn't make sense, I'll try to explain again. Have a nice day!

**Comment by mirzemehdi** [comment]
@jsk41755 yes this can be used in Compose Multiplatform. This is how I used in https://github.com/mirzemehdi/FindTravelNow-KMM/

**Comment by jsk41755** [comment]
Thanks for the answer, I'll look at your project and try to apply it, have a nice day!
