### ISSUE TITLE
Support for desktop (JVM) ?

### ISSUE THREAD

**Issue by DroidZed** [mirzemehdi/KMPNotifier#39]
As the title says, I want to know if they'll be support for desktop KMP?

I'm building an android + desktop (JVM) app and couldn't find a library to help me in my case. It'd be really helpful to know if there will be planned support for desktop targets (JVM, macOS...ect).

Thank you !

**Comment by mirzemehdi** [comment]
@DroidZed currently I am working on that https://github.com/mirzemehdi/KMPNotifier/tree/desktop_support

**Comment by DroidZed** [comment]
Will test it once it arrives !! Thank youu ✨
