### ISSUE TITLE
Error when I try to get a token on iOS.

### ISSUE THREAD

**Issue by tmdgh1592** [mirzemehdi/KMPNotifier#43]
It is a Compose Multiplatform environment and is using kotlin 2.0.0.
When trying to get a token on iOS, the following bug occurs:

```
[FirebaseCore][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI).
```

Firebase Messaging has already been added as an additional xcode dependency.
I wonder what the cause is.

**Comment by mirzemehdi** [comment]
@tmdgh1592 you probably missed ios setup part

https://github.com/mirzemehdi/KMPNotifier?tab=readme-ov-file#ios-setup

in ios application you need this
```FirebaseApp.configure() ```

<img width="1004" alt="image" src="https://github.com/mirzemehdi/KMPNotifier/assets/32781662/502df340-8eef-41c0-8bc8-0b5902d87cb6">

**Comment by tmdgh1592** [comment]
@mirzemehdi 

Thanks for your help 😊
And in the case of iOS, p8 must be registered in Firebase for apnstoken to be issued properly, right?

**Comment by r4m-mirze** [comment]
yes @tmdgh1592

**Comment by mirzemehdi** [comment]
yes @tmdgh1592

**Comment by tmdgh1592** [comment]
@mirzemehdi 
thank you
i will try!

**Comment by tmdgh1592** [comment]
@mirzemehdi 

Hi, I'm still trying to resolve the error.
Although we succeeded in resolving most of the error phrases, there is still one problem remaining.
An error is occurring because APNS Token could not be set in `didRegisterForRemoteNotificationsWithDeviceToken`.
After taking a log, it seems that the function in the didRegisterForRemoteNotificationsWithDeviceToken part is not called at all.
I have configured p8 in Firebase, and I think I have already completed the necessary work, such as setting FirebaseAppDelegateProxyEnabled to NO.
Also, I have referred to both the issues in the repository and stackoverflow to resolve this error, but I have not been able to resolve it yet...
Is there anything to expect bro? 😭

```swift
import SwiftUI
import ComposeApp
import FirebaseCore
import FirebaseMessaging


class AppDelegate: NSObject, UIApplicationDelegate, MessagingDelegate, UNUserNotificationCenterDelegate {

    func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
        FirebaseApp.configure()
        NotifierManager.shared.initialize(configuration: NotificationPlatformConfigurationIos(showPushNotification: true, askNotificationPermissionOnStart: false))
        application.registerForRemoteNotifications()
        Messaging.messaging().token { token, error in
          if let error = error {
            print("Error fetching FCM registration token: \(error)")
          } else if let token = token {
            print("FCM registration token: \(token)")
          }
        }
        return true
    }

    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        print("test log")
        Messaging.messaging().apnsToken = deviceToken
    }
}

@main
struct iOSApp: App {
    @UIApplicationDelegateAdaptor(AppDelegate.self) var delegate
    
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

**Comment by mirzemehdi** [comment]
@tmdgh1592 what is the issue currently? Getting this "Error while getting token: Error Domain=com.google.fcm Code=505 "No APNS token specified before fetching FCM Token" UserInfo={NSLocalizedFailureReason=No APNS token specified before fetching FCM Token}" is expected in ios currently. But when you call getToken you should be able to use it.


Please check this : https://github.com/mirzemehdi/KMPNotifier/issues/3
Please also check this issue as well: https://github.com/mirzemehdi/KMPNotifier/issues/38

**Comment by tmdgh1592** [comment]
@mirzemehdi

Thanks for linking the issue.
I've referenced both issues, but I still can't get the token.
My problem I'm having is that I can't get the token.
And the reason I think is because APNS is not configured

A screenshot of the detailed log is below
thank you

<img width="1489" alt="스크린샷 2024-07-25 오후 10 16 00" src="https://github.com/user-attachments/assets/12ddf8fc-87af-4a95-b5de-fcaf11261207">

**Comment by mirzemehdi** [comment]
Most probably with some configuration in firebase side.  Please try in new project, and check if bundleId is set correctly and p8 file is uploaded

**Comment by ernestkamara** [comment]
Hey @mirzemehdi, I also face the same issue and I'm pretty sure my p8 file is correctly configured. Any chance you could reopen this issue?

**Comment by ernestkamara** [comment]
@tmdgh1592 Did you managed to fix it?
