### ISSUE TITLE
No push notifications received on iOS

### ISSUE THREAD

**Issue by orelvis15** [mirzemehdi/KMPNotifier#48]
I have all the configuration for both platforms, on Android I receive notifications from the first moment, but on iOS when I send a push notification to the token generated by the app, nothing is shown.

Also try using this listener, on Android it works perfectly but on iOS it does not print the message

```
NotifierManager.addListener(object : NotifierManager.Listener {
        override fun onPushNotification(title:String?,body:String?) {
            println("Push Notification notification title: $title")
        }
    })
```

Local notifications are working perfectly for me on both platforms.

**Comment by orelvis15** [comment]
The type is notifications, at the moment I don't need data notifications

I only have this in Logcat.
```
2024-07-09 10:11:28.970405-0500 Neo Mambi[48934:9798458] 10.28.1 - [GoogleUtilities/AppDelegateSwizzler][I-SWZ001011] App Delegate Proxy is disabled.
Library is initialized
FirebasePushNotifier is initialized
FirebaseMessaging: onNewToken is called
```

**Comment by mirzemehdi** [comment]
@orelvis15 @eng-mohamedalmahdy configuration I mean the things on ios setup part, and Don't forget to add Push Notifications and Background Modes (Remote Notifications) signing capability in Xcode.
https://github.com/mirzemehdi/KMPNotifier?tab=readme-ov-file#ios-setup

**Comment by mirzemehdi** [comment]
if possible please link to app sample code

**Comment by eng-mohamedalmahdy** [comment]
> if possible please share link for app sample code

I added all needed capabilities
Configured firebase properly
I can get the firebase token successfully
But didReceiveRemoteNotification is never called

![image](https://github.com/mirzemehdi/KMPNotifier/assets/49305252/cca83c94-e959-4af1-91f1-397b7f633617)
This is my app delegate class

```swift

class AppDelegate: NSObject, UIApplicationDelegate, MessagingDelegate, UNUserNotificationCenterDelegate {

    func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {

        FirebaseApp.configure() //important
        NotifierManager.shared.initialize(
            configuration: NotificationPlatformConfigurationIos(
                showPushNotification: true,
                askNotificationPermissionOnStart: true
            )
        )

        return true
    }

    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        print("Registered for \(deviceToken)")
        Messaging.messaging().apnsToken = deviceToken
    }

    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any]) async -> UIBackgroundFetchResult {
        print(userInfo)
        NotifierManager.shared.onApplicationDidReceiveRemoteNotification(userInfo: userInfo)
        return UIBackgroundFetchResult.newData
    }

}
```

**Comment by mirzemehdi** [comment]
@eng-mohamedalmahdy Does showing local notificaiton works?

**Comment by eng-mohamedalmahdy** [comment]
> @eng-mohamedalmahdy Does showing local notificaiton work?

Yes local notifier works perfectly 
Also tried APNs json on emulator and it also worked

**Comment by mirzemehdi** [comment]
Which version of KMPNotifier library you are using?
if you are using latest `1.1.0` version, can you please check with previous `1.0.1` version. Maybe something is broken on latest version

**Comment by eng-mohamedalmahdy** [comment]
@mirzemehdi  I tried both version but both doesn't seem to work
do you suggest to downgrade to 0.6.0?

> @eng-mohamedalmahdy @orelvis15 Which version of KMPNotifier library you are using? if you are using latest `1.1.0` version, can you please check with previous `1.0.1` version. Maybe something is broken on latest version

**Comment by mirzemehdi** [comment]
I don't think it would have any effect

**Comment by mirzemehdi** [comment]
I just tried latest version, and it was working in ios well. I think it is something related to some configuration issue with firebase, like uploading apn certificate or correct bundleID or other things. Please see "didreceiveremotenotification not called" issues from stackoverflow

**Comment by eng-mohamedalmahdy** [comment]
@mirzemehdi 
> I just tried latest version, and it was working in ios well. I think it is something related to some configuration issue with firebase, like uploading apn certificate or correct bundleID or other things. Please see "didreceiveremotenotification not called" issues from stackoverflow

Never had doubt it's a library issue

Fortunately I got my problem fixed

Initially I changed the bundle ID to a proper named one
deleted the ios app from the firebase
created new app
Downloaded the new plist
Added it to the app
Added my P8 to firebase console
Waited for about 10 minutes
Tried again and every thing worked

Code snippet that may be useful

```kotlin


fun onPayloadDataImpl
(data: Map<String, *>)
 {
    // Extract data
    val aps = data["aps"] as? Map<*, *>
    val alert = aps?.get("alert") as? Map<*, *>
    val title = alert?.get("title") as? String
    val body = alert?.get("body") as? String
    
    if (title != null && body != null) {
        println("Title: $title")
        println("Body: $body")

        // Notify using NotifierManager
        NotifierManager.getLocalNotifier().notify(title, body)
    } else {
        println("Failed to extract title and body from notification payload")
    }
}

object PushNotificationsKit {
    fun initNotificationListener(scope: CoroutineScope) {
        NotifierManager.addListener(
            object : NotifierManager.Listener {
                override fun onNewToken(token: String) {
                    scope.launch {
                        val useCase = KoinPlatform.getKoin().get<RefreshFirebaseTokenUseCase>()
                        when (val response = useCase(token)) {
                            is DomainResponse.Failure -> Napier.d(tag = TAG) { "Failed to refresh token with error ${response.error} $token" }
                            is DomainResponse.Success -> Napier.d(tag = TAG) { "Refresh token Success" }
                        }
                    }
                }

                override fun onNotificationClicked(data: PayloadData) {
                    Napier.d(" Notification clicked $data", tag = TAG)
                    onNotificationClickedImpl(data)
                }

                override fun onPayloadData(data: PayloadData) {
                    Napier.d(" Payload data $data", tag = TAG)
                    onPayloadDataImpl(data)
                }

                override fun onPushNotification(title: String?, body: String?) {
                    val notifier = NotifierManager.getLocalNotifier()
                    Napier.d { "Push notification $title" }
                    notifier.notify(title ?: "", body ?: "")

                }
            }
        )

    }
}

```

**Comment by andiosdev** [comment]
Hi @eng-mohamedalmahdy, did you encounter getting this error message?

APNS device token not set before retrieving FCM Token for Sender ID '-----'.Be sure to re-retrieve the FCM token once the APNS device token is set.

**Comment by andiosdev** [comment]
I was able to get remote push notification for iOS running by following what @eng-mohamedalmahdy did. One thing I noticed in iOS though, notification only appeared while the app is on the background.

**Comment by eng-mohamedalmahdy** [comment]
> I was able to get remote push notification for iOS running by following what @eng-mohamedalmahdy did. One thing I noticed in iOS though, notification only appeared while the app is on the background.

@andiosdev 

I Believe this is a signing & capabilities issue
I just tested the app now in the background and foreground both did work
Please make sure you are using this configurations

![image](https://github.com/user-attachments/assets/d846c820-2ccd-40a8-ad54-c5957d84ab28)

**Comment by orelvis15** [comment]
Hello, good morning, sorry for the delay, what I needed was to upload the .p8 to Firebase, thank you very much for the help!! Regards.
