### ISSUE TITLE
Q: OnPayloadData triggered multiple times on same push notification on iOS side?

### ISSUE THREAD

**Issue by jmsaez2712** [mirzemehdi/KMPNotifier#54]
Hi!
First of all, thank you for this library and the work you are dolng to maintain it. 
But I have a doubt if is a bug or maybe a bad impletentation in my side. 

At the moment, I have push notifications created and sent from a server, that I receive as silent notifications on each platform, Android and iOS on Kotlin Multiplatform. 
I have implemented the clients and all the other stuff, using your app FindTravelNow as example of how to implement FCM. 

The problem I have, is when OnPayloadData is triggered, I receive multiple times the same payload data only on the iOS side.

For example, I receive a two notification from my server side. The first notifications is gonna trigger OnPayloadData 10 times, and then, the second notifications is gonna do the same. It happens with all the notifications.

I checked if something is bad on my server side, but I don't find nothing off. Also, which is make me crazy is the fact that only occurs on iOS side. 

Thank you in advance, and keep working on this amazing library!

**Comment by mirzemehdi** [comment]
@jmsaez2712 Can you please attach logs. Also from server side how do you send notification?(providing curl request would be amazing) So i can reproduce in my side to see what is the issue

**Comment by jmsaez2712** [comment]
Hi @mirzemehdi! Sorry for the late response :(
The iOS app logs, with my payload data:

![image](https://github.com/user-attachments/assets/9e949cf1-67b4-496c-8973-0d20d2775887)
Also, the Curl o REST call to FCM is the following:
```
POST https://fcm.googleapis.com/v1/projects/myproject-b5ae1/messages:send HTTP/1.1

Content-Type: application/json
Authorization: Bearer ya29.ElqKBGN2Ri_Uz...HnS_uNreA //Obtained through the OAuth2 token endpoint through PHP

{
   "message":{
      "token":"bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
      "data":{
        "registrationId": "value"
      }
   }
}
```

**Comment by mirzemehdi** [comment]
@jmsaez2712 can't reproduce it. Please, check maybe from server side it is sent multiple times, or you add multiple listeners in client side.

Also for me in ios when sending above request data type message is not received.

For me this is what works for receiving data type message in ios. **MAIN THING was to add "badge" key** when sending data type notification in order to receive in ios side.
```
{
  "message": {
    "token": "<device_id>",
    "data": "<data>",
    "apns": {
      "payload": {
        "aps": {
          "badge": 0
        }
      }
    }
  }
}

```

**Comment by jmsaez2712** [comment]
@mirzemehdi Also, I forgot to comment about it. The method I'm currently using for fetching the notifications in Swift in App Delegate is a variant of the function you have in the Readme, that FCM specify to use in case you want to receive the notifications when app is in background: 

```
func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult)-> Void)
    {
        NotifierManager.shared.onApplicationDidReceiveRemoteNotification(userInfo: userInfo)
    }
```

Maybe, this can be causing something to go wrong? Because I double and triple checked that I'm not sending duplicates notifications. (But maybe there something I don't see yet) 
Anyway, I will try to implement the part of "badge" key to check if that makes the notifications to not duplicate on onPayloadData method.

**Comment by r4m-mirze** [comment]
@jmsaez2712  that's the main issue part I think. When you call that variant of the code **you also need to call completionHandler function** as  I understand. So use either:

**variant 1 :** 

```
func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult)-> Void)
    {
        NotifierManager.shared.onApplicationDidReceiveRemoteNotification(userInfo: userInfo)
       //TODO: here call completionHandler function
       completionHandler(.newData) 
    }
    
```
    
  **variant 2:**
  
  ```
  func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any]) async -> UIBackgroundFetchResult {
      NotifierManager.shared.onApplicationDidReceiveRemoteNotification(userInfo: userInfo)
      return UIBackgroundFetchResult.newData
 }
 ```

**Comment by mirzemehdi** [comment]
@jmsaez2712  that's the main issue part I think. When you call that variant of the code **you also need to call completionHandler function** as  I understand. So use either:

**variant 1 :** 

```
func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult)-> Void)
    {
        NotifierManager.shared.onApplicationDidReceiveRemoteNotification(userInfo: userInfo)
       //TODO: here call completionHandler function
       completionHandler(.newData) 
    }
    
```
    
  **variant 2:**
  
  ```
  func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any]) async -> UIBackgroundFetchResult {
      NotifierManager.shared.onApplicationDidReceiveRemoteNotification(userInfo: userInfo)
      return UIBackgroundFetchResult.newData
 }
 ```

**Comment by jmsaez2712** [comment]
Hi again @mirzemehdi!
Sorry if you feel that this is something off the initial topic or I'm taking too much of your time. 

But, if I want to use the second variant, iOS block the request I need to do to maintain my app's data updated. So, my only option is the first variant. 
I tested calling the completionHandler, but I still see that onPayloadData is triggered multiple times on receiving a single notification.

**Comment by mirzemehdi** [comment]
Can't help it here since can't reproduce it @jmsaez2712

**Comment by jmsaez2712** [comment]
Okay, don't worry. Thank you anyway for the time you have invested in my issue. 
Keep working on this library, is trully helpful and good!
