### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_FIRMessaging

### ISSUE THREAD

**Issue by ericlamdev** [mirzemehdi/KMPNotifier#69]
**KMPNotifier and Kotlin version:**
 kmpnotifier version: 1.2.1, kotlin version: 2.0.20

**Describe the bug**
I'm trying to build an app with Compose Multiplatform followed the step to add the dependency to the project,

libs.version.xml
```
kmpnotifier = "1.2.1"
kmpnotifier = { module = "io.github.mirzemehdi:kmpnotifier", name = "kmpnotifier", version.ref = "kmpnotifier" }
```

build.gradle.kts
```
    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
            export(libs.kmpnotifier)
        }
    }
    
    commonMain.dependencies {
      ...
      api(libs.kmpnotifier)
    }
```

However when I build the project on Xcode, an error occurred 
![image](https://github.com/user-attachments/assets/7aa65ee6-2860-46d8-a24f-3683c04d67fc)

**In which platform bug occurs?**
iOS

**To Reproduce**
Use Compose Multiplatform and follow the step on the readme, then build the app on Xcode

**Expected behavior**
Build Success

**Additional info to help reproduce**
see the image above

**Comment by marenovakovic** [comment]
Solution?

**Comment by Ashkan-san** [comment]
you need to add the Messaging package in xcode. File -> Add package dependencies -> search for firebase and there select the target for messaging
