### ISSUE TITLE
feat: detect if we received a notification in background or foreground

### ISSUE THREAD

**Issue by jvondermarck** [mirzemehdi/KMPNotifier#71]
Usually, with Firebase Messaging we can listen to background notification so we can know if we receive a notification in background or foreground. But in this library, how could we know if we received a notification in background (when the app is in background or killed) inside a listener method like `onPayloadData` ?

**Comment by mirzemehdi** [comment]
@jvondermarck in firebase how do you know if you received notification in background?

**Comment by jvondermarck** [comment]
@mirzemehdi In flutter, I used the method `listenToBackgroundNotification()` and I declare a method inside so I know if a notification is shown in background or foreground thanks to this. And I used the library `firebase_messaging`.

So how could I know in this library if when we get a notification if it is in background or foreground (in the app) ?

@mirzemehdi

**Comment by mirzemehdi** [comment]
thank you @jvondermarck I'll check that. In this library, as it is in Firebase guide:

So if you receive message when app is in background then data will be in `onPayloadData` 

<img width="993" alt="image" src="https://github.com/user-attachments/assets/a14451f7-eb0e-4989-b9fa-0d578c4d72ab">

**Comment by jvondermarck** [comment]
Thanks for your quick answer. So far, either I am in background or foreground the method `override fun onPayloadData(data: PayloadData)` is called and only these two methods when I listen to `NotifierManager.Listener` so I don't really understand the Firebase guide 😅.

**Comment by mirzemehdi** [comment]
this method is called if you send data type message from Firebase @jvondermarck. Not only if app is in foreground or background

**Comment by jvondermarck** [comment]
Ahhh okay okay, unfortunately I do not manage the Firebase so my work is just to get the notification that's all, so unfortunately
I will always get these notifications in this method. So I guess there isn't any solution yet to know if I am in background or no: I am going to check if I can do something in the androidMain to know.

**Comment by jvondermarck** [comment]
for those who might ask, I did this in Android to know If I am in background or foreground :

In the `commonMain`
```kotlin
// ⚠️ It is still in beta because 'expect'/'actual' classes (including interfaces, objects, annotations, enums, and 'actual' typealiases) are in Beta. Also see: https://youtrack.jetbrains.com/issue/KT-61573
@Suppress("EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
expect object AppState {
    fun isInBackground(): Boolean
}
```

In the `androidMain`
```kotlin
import android.os.Handler
import android.os.Looper
import androidx.lifecycle.DefaultLifecycleObserver
import androidx.lifecycle.LifecycleOwner
import androidx.lifecycle.ProcessLifecycleOwner

@Suppress("EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
actual object AppState : DefaultLifecycleObserver {
    private var isInBackground = true

    init {
        // Ensure this is called on the main thread
        if (Looper.myLooper() == Looper.getMainLooper()) {
            ProcessLifecycleOwner.get().lifecycle.addObserver(this)
        } else {
            Handler(Looper.getMainLooper()).post {
                ProcessLifecycleOwner.get().lifecycle.addObserver(this)
            }
        }
    }

    override fun onStart(owner: LifecycleOwner) {
        isInBackground = false
    }

    override fun onStop(owner: LifecycleOwner) {
        isInBackground = true
    }

    actual fun isInBackground(): Boolean {
        return isInBackground
    }
}
```

And for iOS you could do this
```kotlin
import platform.UIKit.UIApplication
import platform.UIKit.UIApplicationState

@Suppress("EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
actual object AppState {
    actual fun isInBackground(): Boolean {
        val state = UIApplication.sharedApplication.applicationState
        return state == UIApplicationState.UIApplicationStateBackground
    }
}
```

Enjoy ☺️

**Comment by mirzemehdi** [comment]
Amazing. Thank you @jvondermarck . Closing the issue for now, I think this shouldn't be part of the library
