### ISSUE TITLE
Update to Kotlin 2.0.20 & Koin to 4.0.0

### ISSUE THREAD

**Issue by Tweener** [mirzemehdi/KMPNotifier#76]
Hi @mirzemehdi ,

I recently updated my projects to Kotlin 2.0.20 and Koin 4.0.0. And I've faced a compilation issue on iOS, which comes from Koin 4.0.0:
https://github.com/InsertKoinIO/koin/issues/2003

Basically, when updating from Koin 4.0.0-RC1 to 4.0.0, they removed the dependency `com.benasher44:uuid` to instead use the [Kotlin’s standard library UUID](https://kotlinlang.org/docs/whatsnew2020.html#support-for-uuids-in-the-common-kotlin-standard-library).

Since your library is still using Kotlin 2.0.0 and Koin 4.0.0-RC1, you also need to update your library to these versions, so we can keep on using your awesome lib :)

**Comment by mirzemehdi** [comment]
@Tweener thanks for reporting this. For now temporary solution would be to add uuid library into your gradle file, until I release new version with updating koin version

```
implementation("com.benasher44:uuid:0.8.4"
```

**Comment by Tweener** [comment]
Thanks a lot @mirzemehdi ! 👍 
Hopefully you won't face any issue when updating. When I did it, it went pretty smooth and took my like 5 minutes. 🤞

**Comment by mirzemehdi** [comment]
@Tweener @DmitriSerhienko This is implemented in `1.3.0` version.

Now this error shouldn't occur: "error: KLIB resolver: Could not find "com.benasher44:uuid""

**Comment by Tweener** [comment]
Just tested and I confirm the issue is gone. Thank you @mirzemehdi ! 🙏
