### ISSUE TITLE
Suggestion: Android current minSDK  is 24, can be changed to 21. Add android and iOS support versions to README file

### ISSUE THREAD

**Issue by mehmetakify** [mirzemehdi/KMPNotifier#9]
Project **minSdk** for Android is 24. Why?

I added to manifest file `<uses-sdk tools:overrideLibrary="com.mmk.kmpnotifier"/>` and everything works well in the device with **sdk 21**.

I think **minSDK** can change as 21 for Android.

Another advice is about Read Me file. Adding minimum support OS versions can be useful for Android and IOS.

**Comment by mirzemehdi** [comment]
@mehmetakify Thanks for bringing it to my attention. I'll add this to next milestone

**Comment by mirzemehdi** [comment]
This is implemented in version `0.3.0`
