### ISSUE TITLE
How to implement push notification by just firebase FCM token in iOS?

### ISSUE THREAD

**Issue by alexgallardo11** [mirzemehdi/KMPNotifier#90]
How to implement push notification by just firebase FCM token?

in the readme show this implementation:
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Messaging.messaging().apnsToken = deviceToken
  }
  
  but i want to get the token in the common code with this function:
  NotifierManager.getPushNotifier().getToken()
  
  In android is working and i'm reciving notifications, but in ios is not working.
  
  How can i fix it?

**Comment by spporan** [comment]
Why did you close this without any solution? Did you get any solution for this issue?
